// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpgenzhfrwsuwacggyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZ2VuemhmcndzdXdhY2dneWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODY4NjEsImV4cCI6MjA3MzY2Mjg2MX0.Un0QadAOV0j85KhvD0eUlgl9l5zaqUwCm9XPFFnaBLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});